import type { Patient } from './types';

export const patients: Patient[] = [
  {
    id: 'USR001',
    name: 'Aarav Sharma',
    age: 45,
    gender: 'Male',
    sugarLevel: 140,
    bpSystolic: 130,
    bpDiastolic: 85,
    bmi: 28.5,
    riskLevel: 'Medium',
    avatar: 'avatar-1',
  },
  {
    id: 'USR002',
    name: 'Diya Patel',
    age: 62,
    gender: 'Female',
    sugarLevel: 160,
    bpSystolic: 145,
    bpDiastolic: 90,
    bmi: 31.2,
    riskLevel: 'High',
    avatar: 'avatar-2',
  },
  {
    id: 'USR003',
    name: 'Vivaan Singh',
    age: 35,
    gender: 'Male',
    sugarLevel: 110,
    bpSystolic: 120,
    bpDiastolic: 80,
    bmi: 24.0,
    riskLevel: 'Low',
    avatar: 'avatar-3',
  },
  {
    id: 'USR004',
    name: 'Ananya Reddy',
    age: 55,
    gender: 'Female',
    sugarLevel: 130,
    bpSystolic: 135,
    bpDiastolic: 88,
    bmi: 29.8,
    riskLevel: 'Medium',
    avatar: 'avatar-4',
  },
  {
    id: 'USR005',
    name: 'Rohan Gupta',
    age: 70,
    gender: 'Male',
    sugarLevel: 180,
    bpSystolic: 160,
    bpDiastolic: 95,
    bmi: 33.1,
    riskLevel: 'High',
    avatar: 'avatar-5',
  },
  {
    id: 'USR006',
    name: 'Isha Kumar',
    age: 28,
    gender: 'Female',
    sugarLevel: 95,
    bpSystolic: 115,
    bpDiastolic: 75,
    bmi: 22.5,
    riskLevel: 'Low',
    avatar: 'avatar-6',
  },
];
