import type { Patient } from './types';

export const patients: Patient[] = [
  {
    id: 'USR001',
    name: 'Aarav Sharma',
    age: 45,
    gender: 'Male',
    sugarLevel: 140,
    bpSystolic: 130,
    bpDiastolic: 85,
    bmi: 28.5,
    riskLevel: 'Medium',
    avatar: 'avatar-1',
  },
  {
    id: 'USR002',
    name: 'Diya Patel',
    age: 62,
    gender: 'Female',
    sugarLevel: 160,
    bpSystolic: 145,
    bpDiastolic: 90,
    bmi: 31.2,
    riskLevel: 'High',
    avatar: 'avatar-2',
  },
  {
    id: 'USR003',
    name: 'Vivaan Singh',
    age: 35,
    gender: 'Male',
    sugarLevel: 110,
    bpSystolic: 120,
    bpDiastolic: 80,
    bmi: 24.0,
    riskLevel: 'Low',
    avatar: 'avatar-3',
  },
  {
    id: 'USR004',
    name: 'Ananya Reddy',
    age: 55,
    gender: 'Female',
    sugarLevel: 130,
    bpSystolic: 135,
    bpDiastolic: 88,
    bmi: 29.8,
    riskLevel: 'Medium',
    avatar: 'avatar-4',
  },
  {
    id: 'USR005',
    name: 'Rohan Gupta',
    age: 70,
    gender: 'Male',
    sugarLevel: 180,
    bpSystolic: 160,
    bpDiastolic: 95,
    bmi: 33.1,
    riskLevel: 'High',
    avatar: 'avatar-5',
  },
  {
    id: 'USR006',
    name: 'Isha Kumar',
    age: 28,
    gender: 'Female',
    sugarLevel: 95,
    bpSystolic: 115,
    bpDiastolic: 75,
    bmi: 22.5,
    riskLevel: 'Low',
    avatar: 'avatar-6',
  },
  {
    id: 'USR007',
    name: 'Arjun Das',
    age: 58,
    gender: 'Male',
    sugarLevel: 155,
    bpSystolic: 142,
    bpDiastolic: 92,
    bmi: 30.5,
    riskLevel: 'High',
    avatar: 'avatar-7',
  },
  {
    id: 'USR008',
    name: 'Saanvi Joshi',
    age: 42,
    gender: 'Female',
    sugarLevel: 120,
    bpSystolic: 128,
    bpDiastolic: 84,
    bmi: 26.8,
    riskLevel: 'Medium',
    avatar: 'avatar-8',
  },
  {
    id: 'USR009',
    name: 'Kabir Mehta',
    age: 65,
    gender: 'Male',
    sugarLevel: 170,
    bpSystolic: 150,
    bpDiastolic: 94,
    bmi: 32.0,
    riskLevel: 'High',
    avatar: 'avatar-9',
  },
  {
    id: 'USR010',
    name: 'Myra Sharma',
    age: 25,
    gender: 'Female',
    sugarLevel: 100,
    bpSystolic: 110,
    bpDiastolic: 70,
    bmi: 21.3,
    riskLevel: 'Low',
    avatar: 'avatar-10',
  },
  {
    id: 'USR011',
    name: 'Advik Nair',
    age: 51,
    gender: 'Male',
    sugarLevel: 135,
    bpSystolic: 138,
    bpDiastolic: 89,
    bmi: 29.1,
    riskLevel: 'Medium',
    avatar: 'avatar-11',
  },
  {
    id: 'USR012',
    name: 'Kiara Rao',
    age: 75,
    gender: 'Female',
    sugarLevel: 190,
    bpSystolic: 165,
    bpDiastolic: 100,
    bmi: 34.5,
    riskLevel: 'High',
    avatar: 'avatar-12',
  },
  {
    id: 'USR013',
    name: 'Reyansh Verma',
    age: 31,
    gender: 'Male',
    sugarLevel: 105,
    bpSystolic: 118,
    bpDiastolic: 78,
    bmi: 23.5,
    riskLevel: 'Low',
    avatar: 'avatar-13',
  },
  {
    id: 'USR014',
    name: 'Zara Khan',
    age: 48,
    gender: 'Female',
    sugarLevel: 128,
    bpSystolic: 132,
    bpDiastolic: 86,
    bmi: 27.9,
    riskLevel: 'Medium',
    avatar: 'avatar-14',
  },
  {
    id: 'USR015',
    name: 'Ishaan Reddy',
    age: 68,
    gender: 'Male',
    sugarLevel: 175,
    bpSystolic: 155,
    bpDiastolic: 98,
    bmi: 32.8,
    riskLevel: 'High',
    avatar: 'avatar-15',
  },
  {
    id: 'USR016',
    name: 'Anika Singh',
    age: 22,
    gender: 'Female',
    sugarLevel: 98,
    bpSystolic: 112,
    bpDiastolic: 72,
    bmi: 21.8,
    riskLevel: 'Low',
    avatar: 'avatar-1',
  },
  {
    id: 'USR017',
    name: 'Neel Iyer',
    age: 53,
    gender: 'Male',
    sugarLevel: 148,
    bpSystolic: 140,
    bpDiastolic: 91,
    bmi: 30.1,
    riskLevel: 'High',
    avatar: 'avatar-2',
  },
  {
    id: 'USR018',
    name: 'Priya Malhotra',
    age: 39,
    gender: 'Female',
    sugarLevel: 115,
    bpSystolic: 125,
    bpDiastolic: 82,
    bmi: 25.5,
    riskLevel: 'Medium',
    avatar: 'avatar-3',
  },
  {
    id: 'USR019',
    name: 'Ayaan Ali',
    age: 72,
    gender: 'Male',
    sugarLevel: 185,
    bpSystolic: 162,
    bpDiastolic: 97,
    bmi: 33.5,
    riskLevel: 'High',
    avatar: 'avatar-4',
  },
  {
    id: 'USR020',
    name: 'Samaira Desai',
    age: 29,
    gender: 'Female',
    sugarLevel: 102,
    bpSystolic: 114,
    bpDiastolic: 74,
    bmi: 22.1,
    riskLevel: 'Low',
    avatar: 'avatar-5',
  },
  {
    id: 'USR021',
    name: 'Arnav Choudhary',
    age: 46,
    gender: 'Male',
    sugarLevel: 138,
    bpSystolic: 134,
    bpDiastolic: 87,
    bmi: 28.9,
    riskLevel: 'Medium',
    avatar: 'avatar-6',
  },
  {
    id: 'USR022',
    name: 'Riya Verma',
    age: 61,
    gender: 'Female',
    sugarLevel: 165,
    bpSystolic: 148,
    bpDiastolic: 93,
    bmi: 31.8,
    riskLevel: 'High',
    avatar: 'avatar-7',
  },
  {
    id: 'USR023',
    name: 'Dev Mehra',
    age: 33,
    gender: 'Male',
    sugarLevel: 108,
    bpSystolic: 122,
    bpDiastolic: 79,
    bmi: 24.2,
    riskLevel: 'Low',
    avatar: 'avatar-8',
  },
  {
    id: 'USR024',
    name: 'Sia Khanna',
    age: 57,
    gender: 'Female',
    sugarLevel: 152,
    bpSystolic: 144,
    bpDiastolic: 91,
    bmi: 30.9,
    riskLevel: 'High',
    avatar: 'avatar-9',
  },
  {
    id: 'USR025',
    name: 'Zain Abdullah',
    age: 40,
    gender: 'Male',
    sugarLevel: 122,
    bpSystolic: 129,
    bpDiastolic: 85,
    bmi: 27.2,
    riskLevel: 'Medium',
    avatar: 'avatar-10',
  },
  {
    id: 'USR026',
    name: 'Tara Menon',
    age: 69,
    gender: 'Female',
    sugarLevel: 178,
    bpSystolic: 158,
    bpDiastolic: 99,
    bmi: 33.8,
    riskLevel: 'High',
    avatar: 'avatar-11',
  },
  {
    id: 'USR027',
    name: 'Krish Shah',
    age: 26,
    gender: 'Male',
    sugarLevel: 101,
    bpSystolic: 116,
    bpDiastolic: 76,
    bmi: 22.8,
    riskLevel: 'Low',
    avatar: 'avatar-12',
  },
  {
    id: 'USR028',
    name: 'Anjali Pillai',
    age: 50,
    gender: 'Female',
    sugarLevel: 133,
    bpSystolic: 136,
    bpDiastolic: 88,
    bmi: 28.3,
    riskLevel: 'Medium',
    avatar: 'avatar-13',
  },
  {
    id: 'USR029',
    name: 'Vihaan Agarwal',
    age: 63,
    gender: 'Male',
    sugarLevel: 168,
    bpSystolic: 152,
    bpDiastolic: 96,
    bmi: 32.5,
    riskLevel: 'High',
    avatar: 'avatar-14',
  },
  {
    id: 'USR030',
    name: 'Eva Sharma',
    age: 38,
    gender: 'Female',
    sugarLevel: 112,
    bpSystolic: 124,
    bpDiastolic: 81,
    bmi: 25.1,
    riskLevel: 'Low',
    avatar: 'avatar-15',
  },
  {
    id: 'USR031',
    name: 'Yash Gupta',
    age: 49,
    gender: 'Male',
    sugarLevel: 130,
    bpSystolic: 133,
    bpDiastolic: 86,
    bmi: 28.0,
    riskLevel: 'Medium',
    avatar: 'avatar-1',
  },
  {
    id: 'USR032',
    name: 'Avani Singh',
    age: 71,
    gender: 'Female',
    sugarLevel: 182,
    bpSystolic: 161,
    bpDiastolic: 98,
    bmi: 33.3,
    riskLevel: 'High',
    avatar: 'avatar-2',
  },
  {
    id: 'USR033',
    name: 'Arin Kumar',
    age: 30,
    gender: 'Male',
    sugarLevel: 104,
    bpSystolic: 117,
    bpDiastolic: 77,
    bmi: 23.1,
    riskLevel: 'Low',
    avatar: 'avatar-3',
  },
  {
    id: 'USR034',
    name: 'Aisha Rao',
    age: 54,
    gender: 'Female',
    sugarLevel: 145,
    bpSystolic: 139,
    bpDiastolic: 90,
    bmi: 29.5,
    riskLevel: 'Medium',
    avatar: 'avatar-4',
  },
  {
    id: 'USR035',
    name: 'Om Patel',
    age: 66,
    gender: 'Male',
    sugarLevel: 172,
    bpSystolic: 154,
    bpDiastolic: 97,
    bmi: 32.2,
    riskLevel: 'High',
    avatar: 'avatar-5',
  },
  {
    id: 'USR036',
    name: 'Navya Reddy',
    age: 24,
    gender: 'Female',
    sugarLevel: 97,
    bpSystolic: 111,
    bpDiastolic: 71,
    bmi: 21.6,
    riskLevel: 'Low',
    avatar: 'avatar-6',
  },
  {
    id: 'USR037',
    name: 'Sai Prasad',
    age: 52,
    gender: 'Male',
    sugarLevel: 142,
    bpSystolic: 137,
    bpDiastolic: 88,
    bmi: 29.3,
    riskLevel: 'Medium',
    avatar: 'avatar-7',
  },
  {
    id: 'USR038',
    name: 'Mahi Jain',
    age: 60,
    gender: 'Female',
    sugarLevel: 158,
    bpSystolic: 146,
    bpDiastolic: 92,
    bmi: 31.5,
    riskLevel: 'High',
    avatar: 'avatar-8',
  },
  {
    id: 'USR039',
    name: 'Kian Sharma',
    age: 36,
    gender: 'Male',
    sugarLevel: 114,
    bpSystolic: 126,
    bpDiastolic: 83,
    bmi: 26.2,
    riskLevel: 'Medium',
    avatar: 'avatar-9',
  },
  {
    id: 'USR040',
    name: 'Aditi Bose',
    age: 47,
    gender: 'Female',
    sugarLevel: 126,
    bpSystolic: 131,
    bpDiastolic: 85,
    bmi: 27.6,
    riskLevel: 'Medium',
    avatar: 'avatar-10',
  },
  {
    id: 'USR041',
    name: 'Rudra Singh',
    age: 67,
    gender: 'Male',
    sugarLevel: 174,
    bpSystolic: 156,
    bpDiastolic: 98,
    bmi: 32.7,
    riskLevel: 'High',
    avatar: 'avatar-11',
  },
  {
    id: 'USR042',
    name: 'Ira Saxena',
    age: 23,
    gender: 'Female',
    sugarLevel: 96,
    bpSystolic: 110,
    bpDiastolic: 70,
    bmi: 21.5,
    riskLevel: 'Low',
    avatar: 'avatar-12',
  },
  {
    id: 'USR043',
    name: 'Arush Menon',
    age: 56,
    gender: 'Male',
    sugarLevel: 150,
    bpSystolic: 143,
    bpDiastolic: 91,
    bmi: 30.7,
    riskLevel: 'High',
    avatar: 'avatar-13',
  },
  {
    id: 'USR044',
    name: 'Anvi Gupta',
    age: 43,
    gender: 'Female',
    sugarLevel: 124,
    bpSystolic: 130,
    bpDiastolic: 84,
    bmi: 27.4,
    riskLevel: 'Medium',
    avatar: 'avatar-14',
  },
  {
    id: 'USR045',
    name: 'Abeer Khan',
    age: 73,
    gender: 'Male',
    sugarLevel: 188,
    bpSystolic: 164,
    bpDiastolic: 101,
    bmi: 34.1,
    riskLevel: 'High',
    avatar: 'avatar-15',
  },
  {
    id: 'USR046',
    name: 'Pari Sharma',
    age: 30,
    gender: 'Female',
    sugarLevel: 103,
    bpSystolic: 115,
    bpDiastolic: 75,
    bmi: 22.9,
    riskLevel: 'Low',
    avatar: 'avatar-1',
  },
  {
    id: 'USR047',
    name: 'Dhruv Kumar',
    age: 44,
    gender: 'Male',
    sugarLevel: 129,
    bpSystolic: 132,
    bpDiastolic: 86,
    bmi: 27.8,
    riskLevel: 'Medium',
    avatar: 'avatar-2',
  },
  {
    id: 'USR048',
    name: 'Amaira Singh',
    age: 59,
    gender: 'Female',
    sugarLevel: 156,
    bpSystolic: 145,
    bpDiastolic: 92,
    bmi: 31.3,
    riskLevel: 'High',
    avatar: 'avatar-3',
  },
  {
    id: 'USR049',
    name: 'Atharv Reddy',
    age: 32,
    gender: 'Male',
    sugarLevel: 107,
    bpSystolic: 121,
    bpDiastolic: 79,
    bmi: 23.9,
    riskLevel: 'Low',
    avatar: 'avatar-4',
  },
  {
    id: 'USR050',
    name: 'Khushi Patel',
    age: 64,
    gender: 'Female',
    sugarLevel: 169,
    bpSystolic: 151,
    bpDiastolic: 95,
    bmi: 32.3,
    riskLevel: 'High',
    avatar: 'avatar-5',
  },
  {
    id: 'USR051',
    name: 'Laksh Sharma',
    age: 41,
    gender: 'Male',
    sugarLevel: 118,
    bpSystolic: 127,
    bpDiastolic: 83,
    bmi: 26.5,
    riskLevel: 'Medium',
    avatar: 'avatar-6',
  },
  {
    id: 'USR052',
    name: 'Shanaya Gupta',
    age: 27,
    gender: 'Female',
    sugarLevel: 99,
    bpSystolic: 113,
    bpDiastolic: 73,
    bmi: 22.3,
    riskLevel: 'Low',
    avatar: 'avatar-7',
  },
];
